# Generated by Django 3.1.3 on 2021-09-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=100)),
                ('mName', models.CharField(max_length=100)),
                ('lName', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateTimeField()),
                ('zip', models.DecimalField(blank=True, decimal_places=1.0, max_digits=4, null=True)),
            ],
        ),
    ]
