# Generated by Django 3.1.3 on 2021-11-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(default='no address', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(default='no city', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='emailInfo',
            field=models.EmailField(default='No email provided', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fName',
            field=models.CharField(default='First name not given', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lName',
            field=models.CharField(default='Last name not given', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mName',
            field=models.CharField(default='Middle name not given', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phoneInfo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='zip',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=5, null=True),
        ),
    ]
