# Generated by Django 3.1.3 on 2021-10-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='dataPurge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='api',
            name='dataReport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='api',
            name='dataRetrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='api',
            name='radio1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='api',
            name='radio2',
            field=models.BooleanField(default=False),
        ),
    ]
