# Generated by Django 3.1.3 on 2021-10-03 02:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='api',
            name='fName',
        ),
        migrations.RemoveField(
            model_name='api',
            name='lName',
        ),
        migrations.RemoveField(
            model_name='api',
            name='mName',
        ),
        migrations.AddField(
            model_name='api',
            name='address',
            field=models.CharField(max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='address2',
            field=models.CharField(max_length=300, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='city',
            field=models.CharField(max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='emailInfo',
            field=models.EmailField(max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='phoneInfo',
            field=models.DecimalField(decimal_places=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='api',
            name='zip',
            field=models.DecimalField(blank=True,max_digits=5, null=True),
        ),
    ]
