# Generated by Django 3.1.3 on 2021-10-03 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211003_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='api',
            name='address',
            field=models.CharField(null=True,blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='api',
            name='city',
            field=models.CharField(null=True,blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='api',
            name='emailInfo',
            field=models.EmailField(null=True,blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='api',
            name='phoneInfo',
            field=models.DecimalField(null=True, blank=True, decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='api',
            name='zip',
            field=models.DecimalField(null=True, blank=True, decimal_places=0, default='12345', max_digits=5),
            preserve_default=False,
        ),
    ]
