# Generated by Django 3.1.3 on 2022-10-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211102_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamethod',
            name='actionType',
            field=models.CharField(default='Enter the action Item', max_length=300),
        ),
        migrations.AddField(
            model_name='datamethod',
            name='extraInfo',
            field=models.CharField(default='Enter extra Info', max_length=300),
        ),
    ]
