# Generated by Django 3.1.3 on 2021-10-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211003_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='address2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
