# Generated by Django 3.1.3 on 2021-10-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211003_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='emailInfo',
            field=models.EmailField(blank=True, default='No email provided', max_length=100),
        ),
    ]
