# Generated by Django 3.1.3 on 2021-10-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211003_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='DOB',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='api',
            name='SSN',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='api',
            name='fName',
            field=models.CharField(blank=True, default='First name not given', max_length=300),
        ),
        migrations.AddField(
            model_name='api',
            name='lName',
            field=models.CharField(blank=True, default='Last name not given', max_length=300),
        ),
        migrations.AddField(
            model_name='api',
            name='mName',
            field=models.CharField(blank=True, default='Middle name not given', max_length=300),
        ),
    ]
