# Generated by Django 3.1.3 on 2021-10-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211004_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='DOB',
            field=models.DateTimeField(blank=True),
        ),
    ]
