# Generated by Django 3.1.3 on 2021-10-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211004_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='DOB',
        ),
    ]
